exports.eventEmitterConstants = {
    ADD_OBJECT_DATA : "ADD_OBJECT_DATA",
    ROTATE_OBJECT : "ROTATE_OBJECT",
    SCALE_OBJECT : "SCALE_OBJECT",
    DRAG_OBJECT : "DRAG_OBJECT",
    CHANGE_MATERIAL_COLOR : "CHANGE_MATERIAL_COLOR",
    DELETE_OBJECT : "DELETE_SELECTED_OBJECT",
    SET_SELECTED_OBJECT : "SET_SELECTED_OBJECT",
    REPLACE_STATE_FROM_SAVE : "REPLACE_STATE_FROM_SAVE",
    COPY_MODEL : "COPY_MODEL",
    PASTE_MODEL : "PASTE_MODEL",
    UNSET_SELECTED_OBJECT : "UNSET_SELECTED_OBJECT",
    HOVER_MODEL : "HOVER_MODEL",
    UNHOVER_MODEL : "UNHOVER_MODEL",
    CHANGE_PLANE_TEXTURE: "CHANGE_PLANE_TEXTURE"
};